### ISSUE TITLE
utaunt doesnt work

### ISSUE THREAD

**Issue by binbonn** [PrikolMen/unknown-taunts#1]
Utaunt is only working in singleplayer,in dedicated servers(mine included)not working,and there isnt any lua error codes.
When you try to choose any dance in menu nothing happens.
Is this problem happening only in my server?
please contact with me on discord : binbontr

**Comment by unknown-gd** [comment]
Not sure about your server, but you're the first to mention it.

**Comment by binbonn** [comment]
okey now fixed thanks prikol
(If your server is darkrp, you need to set act to true and upload the models to the server.)
